In [1]:
import numpy as np

In [11]:
myarr= np.array([3,4,56,8])
myarr

array([ 3,  4, 56,  8])

In [12]:
myarr.dtype

dtype('int32')

In [13]:
myarr.shape

(4,)

In [14]:
myarr= np.array([[3,4,56,8]])
myarr

array([[ 3,  4, 56,  8]])

In [15]:
myarr.shape

(1, 4)

In [17]:
listarr= np.array([[1,2,3],[3,2,5],[4,5,8]])
listarr

array([[1, 2, 3],
       [3, 2, 5],
       [4, 5, 8]])

In [18]:
listarr.shape

(3, 3)

In [20]:
zeros=np.zeros((2,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
r=np.arange(5)
r

array([0, 1, 2, 3, 4])

In [23]:
lspace= np.linspace(1,5,11)
lspace

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. ])

In [24]:
95,5emp=np.empty((5,6))
emp

array([[1.23077750e-311, 9.78249979e-322, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 5.02034658e+175],
       [3.42347494e-032, 2.47148058e-056, 1.13070911e-042,
        4.32115810e-061, 9.73081342e-072, 3.59751658e+252],
       [8.93185432e+271, 7.33723594e+223, 1.47763641e+248,
        1.16096346e-028, 7.69165785e+218, 1.35617292e+248],
       [3.49242350e-033, 2.36784999e+179, 2.42145227e-052,
        6.76272790e+170, 7.43696739e-144, 1.16097020e-028],
       [6.37113545e-067, 2.26301105e-076, 1.91789755e-076,
        1.11763122e+261, 1.16318408e-028, 6.79764374e-310]])

In [25]:
emp_like=np.empty_like(lspace)

In [26]:
emp_like

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. ])

In [29]:
ide= np.identity(4)
ide

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [38]:
arr.reshape(2,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [42]:
arr = np.arange(50)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [43]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [40]:
arr.shape

(50,)

In [44]:
ar= np.array([[2,3],[4,5]])
ar

array([[2, 3],
       [4, 5]])

In [45]:
ar.sum(axis=1)

array([5, 9])

In [46]:
ar.T

array([[2, 4],
       [3, 5]])

In [47]:
for item in ar.flat:
    print(item)

2
3
4
5
